POST HTTP://localhost:4000/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlYWYyOTEyLWRiNTUtNDRjOC1hODA4LTkwMTk2ZTdiOTVjZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyNzkyMzY0NywiZXhwIjoxNzI3OTI3MjQ3fQ.X9fl_kUCQU77WLO9pO6k-alsfVjvdH316Vd9be36duY

{
    "title": "titulo de prueba2",
    "linkTitle": "titulo_de_prueba2",
    "tags": ["tag2"],
    "cardImage": "img2",
    "description": "descripcion2",
    "content": "contenido2"
}

###

GET HTTP://localhost:4000/api/blogs HTTP/1.1

###

GET HTTP://localhost:4000/api/blogs/2281742a-774e-4514-b0cc-214adc872333 HTTP/1.1

###

PUT HTTP://localhost:4000/api/blogs/deaf2912-db55-44c8-a808-90196e7b95ce HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlYWYyOTEyLWRiNTUtNDRjOC1hODA4LTkwMTk2ZTdiOTVjZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyNzkyMzY0NywiZXhwIjoxNzI3OTI3MjQ3fQ.X9fl_kUCQU77WLO9pO6k-alsfVjvdH316Vd9be36duY

{
    "title": "Blog de prueba *(editado)"
}

###

DELETE HTTP://localhost:4000/api/blogs/deaf2912-db55-44c8-a808-90196e7b95ce HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlYWYyOTEyLWRiNTUtNDRjOC1hODA4LTkwMTk2ZTdiOTVjZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyNzkyMzY0NywiZXhwIjoxNzI3OTI3MjQ3fQ.X9fl_kUCQU77WLO9pO6k-alsfVjvdH316Vd9be36duY
